### PR TITLE
Add section for running BioCro in Welsch RStudio

### PR DESCRIPTION
**Pull request by KristinaRiemer**
Does the same thing as in the VM but in UA's interface.

### CODE REVIEW

**Comment by KristinaRiemer** [comment]
@tarinzin, I don't have enough permissions to make you an official reviewer, but if you have time I was hoping you could go through this vignette? Specifically, the "BioCro Run Using University of Arizona's RStudio Instance" section in the biocro_in_pecan.pdf. I'm interested in what parts need more instructions and if anything doesn't work.

**Comment by tarinzin** [comment]
Yes, I want to use BioCrop, and I think it's a good idea to follow your vignette. You sent me a couple of pdf files for BioCrop and ED2 a month ago. Is that pdf you are talking about? I cannot see the link here to for biocrop_in_pecan.pdf. Also, I am trying to login in Arizona RStudio Instance. Was our last names the password? How can I recover my account? Cheers

**Comment by KristinaRiemer** [comment]
@tarinzin those PDFs from before are old ones that don't have the new stuff for you to look at. You can see the files by clicking on the "Files changed" tab at the top of this page. The green shows what has been added. You can see the changes in the raw file, which is called biocro_in_pecan.Rmd, but the PDF version of it isn't shown because it's a binary file. In order to get the PDF yourself, you'd have to get this pull request as a branch on a local copy of this repository, which is a little tricky to do, so I'll just send you the PDF over Slack. I can also tell you your login info there.

**Comment by KristinaRiemer** [comment]
Reviewed by @tarinzin, made a couple of fixes. This looks good now.

**Pull request merged**
